name: Generate ISO Pipelines

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install host dependencies
      env:
        GZIP: -9
      run: |
          wget http://ftp.us.debian.org/debian/pool/main/l/linux-signed-arm64/linux-image-6.5.0-5-arm64_6.5.13-1_arm64.deb
          ar x linux-image-6.5.0-5-arm64_6.5.13-1_arm64.deb
          sudo rm /boot/config-*
          mkdir linux-kernel
          dpkg-deb -xv linux-image-6.5.0-5-arm64_6.5.13-1_arm64.deb linux-kernel
          sudo cp linux-kernel/boot/config-6.5.0-5-arm64 /boot
          sudo apt-get update -y
          sudo apt-get install -y git xz-utils crossbuild-essential-arm64 debhelper build-essential linux-source bc kmod cpio flex libncurses5-dev libelf-dev libssl-dev dwarves bison
          git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git --depth=1
          sudo cp linux-kernel/boot/config-6.5.0-5-arm64 linux/.config
          cd linux
          scripts/config --disable DEBUG_INFO
          scripts/config --disable SYSTEM_TRUSTED_KEYS
          scripts/config --disable SYSTEM_REVOCATION_KEYS
          scripts/config --set-val CONFIG_MODULE_COMPRESS_XZ 'y'
          
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j `nproc` bindeb-pkg
          cd ..

    
    - name: upload rpi4b artifact
      uses: actions/upload-artifact@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        path: linux-image-*.deb
        name: linux-image-arm64.deb
