name: Generate ISO Pipelines

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install host dependencies
      env:
        GZIP: -9
      run: |
          wget http://ftp.us.debian.org/debian/pool/main/l/linux/linux-image-6.6-arm64-unsigned_6.6.3-1~exp1_arm64.deb
          ar x linux-image-6.6-arm64-unsigned_6.6.3-1~exp1_arm64.deb
          sudo rm /boot/config-*
          tar data.tar.gz
          ls .
          sudo cp boot/config-6.6-arm64 /boot
          sudo apt-get update -y
          sudo apt-get install -y git crossbuild-essential-arm64 debhelper build-essential linux-source bc kmod cpio flex libncurses5-dev libelf-dev libssl-dev dwarves bison
          git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git --depth=1
          cd linux
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig
          scripts/config --disable DEBUG_INFO
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j `nproc` bindeb-pkg
          cd ..

    
    - name: upload rpi4b artifact
      uses: actions/upload-artifact@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        path: linux-image-*.deb
        name: linux-image-arm64.deb
